# Generated by Django 2.0.4 on 2020-03-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('grade', models.IntegerField(max_length=11)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
