# Generated by Django 2.0.4 on 2020-03-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_user_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
    ]
